name: bats

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  GO_VERSION: "1.25"
  K8S_VERSION: "v1.35.0"
  KIND_VERSION: "v0.31.0"

jobs:
  bats_tests:
    runs-on: ubuntu-22.04
    name: Bats e2e tests
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup Bats and bats libs
        id: setup-bats
        uses: bats-core/bats-action@77d6fb60505b4d0d1d73e48bd035b55074bbfb43 # 4.0.0

      - name: Bats tests
        shell: bash
        env:
         BATS_LIB_PATH: ${{ steps.setup-bats.outputs.lib-path }}
         TERM: xterm
        run: |
          bats -o _artifacts tests/

      - name: Bats tests (custom network)
        shell: bash
        env:
          BATS_LIB_PATH: ${{ steps.setup-bats.outputs.lib-path }}
          TERM: xterm
        run: |
          bats -o _artifacts-custom-network tests/custom-network/

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v5
        with:
          name: kind-logs-${{ env.JOB_NAME }}-${{ github.run_id }}
          path: |
            ./_artifacts
            ./_artifacts-custom-network
 
  bats_mac_tests:
    runs-on: macos-15-intel
    name: Bats e2e tests on Mac
    # Skip until runner does not timeout on kind create cluster
    if: false
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      # c.f. https://github.com/actions/runner-images/issues/13358
      - name: Work around x86 macOS bug for multiple CPU cores
        run: |
          sudo defaults -currentHost write /Library/Preferences/com.apple.powerlogd SMCMonitorCadence 0
          sudo killall PerfPowerServices || true
      - name: Set up environment (download dependencies)
        run: |
          brew install docker colima
          brew install kind
          brew install golang
          brew install bats-core
          brew install kubectl
          LIMA_SSH_PORT_FORWARDER=true colima start
      - name: Bats tests
        env:
          TERM: linux
        run: |
          bash -c "time bats -o _artifacts --trace --formatter tap tests/"
      - name: Debug info
        if: always()
        run: |
          docker ps
          kubectl get pods -v7
          kubectl get services -v7

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v5
        with:
          name: kind-logs-mac-${{ github.run_id }}
          path: ./_artifacts
